// 	******* HACK ASM FILE GENERATED BY VM COMPILER *******
// 	VM  FILE: SimpleAdd.vm
// 	COMPILER: JAVA_HACK_VM_COMPILER
// 	GEN TIME: 15-9-19 上午12:52


// 'push constant 7' (Line 0)
@7
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 8' (Line 1)
@8
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'add' (Line 2)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=D+M
@SP
M=M+1
